config/routes.rb
Rails.application.routes.draw do
  # verb path '/dfdss', to: 'controller#action'
  # #DISPLAY ALL RESTAURANT (R)
  # get '/restaurants', to: 'restaurants#index'

  # # CREATE A RESTAURANT (C)
  # get '/restaurants/new', to: 'restaurants#new'
  # post '/restaurants', to: 'restaurants#create'

  # # DISPLAY A SINGL/restaurants/:idE RESTAURANT (R)
  # get '', to: 'restaurants#show', as: :restaurant

  # # UPDATE A RESTAURANT (U)
  # get '/restaurants/:id/edit', to: 'restaurants#edit'
  # patch '/restaurants/:id', to: 'restaurants#update'

  # delete '/restaurants/:id', to: 'restaurants#destroy'
  resources :restaurants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :rating, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [ :show, :edit, :update, :destroy ]

  def index
    @restaurants = Restaurant.all
  end

  def show
    # @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant) # SHOW PAGE OF THE RESTAURANT
  end

  def edit
    # @restaurant = Restaurant.find(params[:id])
  end

  def update
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<%= link_to 'New Restaurant', new_restaurant_path  %>

<% @restaurants.each do |restaurant| %>
  <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
  <p><%= '🌶' * restaurant.rating %></p>
  <p><%= restaurant.address %></p>
<% end %>

app/views/restaurants/new.html.erb
<!-- <form action="/restaurants" method="post">
  <label for="name">Name</label>
  <input type="text" name="restaurant[name]">
  <label for="">Rating</label>
  <input type="number" name="restaurant[rating]">
  <label for="">Address</label>
  <input type="text" name="restaurant[address]">
  <input type="submit">
</form> -->
<!--
params = {
  restaurant: {
  name: 'McDonalds',
  rating: 4,
  address: 'Berlin'
}
}

Restaurant.new(name: params[:restaurant], rating: params[:restaurant]) -->

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= '🌶' * @restaurant.rating  %></p>
<p><%= @restaurant.address %></p>

<%= link_to 'Edit restaurant', edit_restaurant_path(@restaurant) %>

<%= link_to 'Delete Restaurant', restaurant_path(@restaurant), method: :delete, data: { confirm: 'Are you sure you want to delete?' }   %>